-- ============================================================
-- AMOS V11：Counters / Measure Points 读数日志 + 演示种子
-- ------------------------------------------------------------
-- 1) counter_reading_log          组件/功能计数器不可变读数日志
-- 2) measure_point_reading_log    组件测点不可变读数日志
-- 3) 种子：C-TEST-10（装在 FN-ENG-01）的计数器/测点 + FN-ENG-01 功能计数器，
--    以及 C-TEST-01 作为级联源（C-TEST-10 的 HRS 计数器 dependsOn=C-TEST-01），
--    支撑模块 07 浏览器/手工验证（读数更新→日志+当前值+平均+级联+function 同步）。
-- H2(PostgreSQL 兼容模式) 与 PostgreSQL 双兼容，全部 IF NOT EXISTS，幂等。
-- 不改动历史 migration。
-- ============================================================

-- 1) 组件/功能计数器读数日志（不可变）
create table if not exists counter_reading_log (
    id                   bigint generated by default as identity primary key,
    component_counter_id bigint,
    component_no         varchar(50),
    function_no          varchar(50),
    code                 varchar(50),
    description          varchar(200),
    old_value            numeric(18, 4),
    new_value            numeric(18, 4),
    delta                numeric(18, 4),
    reading_date         varchar(20),
    created_at           timestamp,
    created_by           varchar(50)
);
create index if not exists idx_crl_component     on counter_reading_log (component_no);
create index if not exists idx_crl_function      on counter_reading_log (function_no);
create index if not exists idx_crl_counter       on counter_reading_log (component_counter_id);
create index if not exists idx_crl_reading_date  on counter_reading_log (reading_date);

-- 2) 组件测点读数日志（不可变）
create table if not exists measure_point_reading_log (
    id                          bigint generated by default as identity primary key,
    component_measure_point_id bigint,
    component_no                varchar(50),
    function_no                 varchar(50),
    code                        varchar(50),
    description                 varchar(200),
    reading_value               varchar(255),
    trend                       varchar(20),
    reading_date                varchar(20),
    created_at                  timestamp,
    created_by                  varchar(50)
);
create index if not exists idx_mpl_component     on measure_point_reading_log (component_no);
create index if not exists idx_mpl_function      on measure_point_reading_log (function_no);
create index if not exists idx_mpl_measure_point on measure_point_reading_log (component_measure_point_id);
create index if not exists idx_mpl_reading_date  on measure_point_reading_log (reading_date);

-- 3) 修正 C-TEST-10 安装关系：V10 已置 function.installed_component_no='C-TEST-10'，
--    此处补齐 component.function_no 使其双向一致（早期 PG 库可能由旧版 V10 造数缺该列）。
update component
   set function_no = 'FN-ENG-01', status = 'In Use'
 where number = 'C-TEST-10' and installation = 'Traveller'
   and (function_no is null or function_no = '');

-- 同步 function.installed_component_no（修正早期 PG 库 FN-ENG-01 误装 C-TEST-01 的漂移）
update maintenance_function
   set installed_component_no = 'C-TEST-10'
 where function_no = 'FN-ENG-01' and installation = 'Traveller';

-- 5) 种子：组件计数器（C-TEST-10 已装 FN-ENG-01；C-TEST-01 为级联源）
insert into component_counter (component_id, code, description, unit, current_value, depends_on, latest_zeroed_date)
select c.id, 'HRS', 'Running Hours', 'h', 900.0, 'C-TEST-01', '2026-01-15'
from component c
where c.number = 'C-TEST-10'
  and not exists (
    select 1 from component_counter cc
    join component c2 on c2.id = cc.component_id
    where c2.number = 'C-TEST-10' and cc.code = 'HRS');

insert into component_counter (component_id, code, description, unit, current_value, depends_on, latest_zeroed_date)
select c.id, 'OIL', 'Lub Oil Pressure', 'bar', 4.5, null, '2026-01-15'
from component c
where c.number = 'C-TEST-10'
  and not exists (
    select 1 from component_counter cc
    join component c2 on c2.id = cc.component_id
    where c2.number = 'C-TEST-10' and cc.code = 'OIL');

insert into component_counter (component_id, code, description, unit, current_value, depends_on, latest_zeroed_date)
select c.id, 'HRS', 'Running Hours', 'h', 900.0, null, '2026-01-15'
from component c
where c.number = 'C-TEST-01'
  and not exists (
    select 1 from component_counter cc
    join component c2 on c2.id = cc.component_id
    where c2.number = 'C-TEST-01' and cc.code = 'HRS');

-- 6) 种子：组件测点（C-TEST-10）
insert into component_measure_point (component_id, code, description, unit, trend, reading, last_read_date)
select c.id, 'T-EXH', 'Exhaust Temp', '°C', 'Stable', '420', '2026-07-28'
from component c
where c.number = 'C-TEST-10'
  and not exists (
    select 1 from component_measure_point mp
    join component c2 on c2.id = mp.component_id
    where c2.number = 'C-TEST-10' and mp.code = 'T-EXH');

-- 7) 种子：功能位置计数器（FN-ENG-01 与组件 HRS 同 description，供同步）
insert into function_counter (function_id, code, description, unit, last_value)
select f.id, 'HRS', 'Running Hours', 'h', 5000.0
from maintenance_function f
where f.function_no = 'FN-ENG-01' and f.installation = 'Traveller'
  and not exists (
    select 1 from function_counter fc
    join maintenance_function f2 on f2.id = fc.function_id
    where f2.function_no = 'FN-ENG-01' and f2.installation = 'Traveller' and fc.code = 'HRS');
