-- ============================================================
-- AMOS Phase 1 初始化：核心表结构 + 种子数据
-- 对应 mock/index.js 的 makerRegistry / components / stockTypes
-- ============================================================

create table if not exists maker_register (
    id   bigint generated by default as identity primary key,
    code varchar(50)  not null unique,
    name varchar(255)
);

create table if not exists component_type (
    id                 bigint generated by default as identity primary key,
    type_number        varchar(50) unique,
    name               varchar(255),
    maker              varchar(50),
    model              varchar(100),
    type               varchar(50),
    class_code         varchar(50),
    preferred_vendor   varchar(255),
    parent_type_number varchar(50),
    description        varchar(1000),
    status             varchar(50),
    date_created       varchar(20),
    date_modified      varchar(20)
);

create table if not exists component (
    id            bigint generated by default as identity primary key,
    number        varchar(50) unique,
    type_number   varchar(50),
    name          varchar(255),
    status        varchar(50),
    maker         varchar(50),
    type          varchar(50),
    serial_no     varchar(100),
    location      varchar(100),
    department    varchar(100),
    vendor        varchar(255),
    function_no   varchar(50),
    install_date  varchar(20),
    installation  varchar(50)
);

create table if not exists component_counter (
    id            bigint generated by default as identity primary key,
    component_id  bigint references component (id),
    code          varchar(50),
    description   varchar(255),
    unit          varchar(20),
    current_value double precision,
    depends_on    varchar(50)
);

create table if not exists stock_type (
    id            bigint generated by default as identity primary key,
    stock_type_no varchar(50) unique,
    description   varchar(255),
    maker         varchar(50),
    makers_ref    varchar(100),
    vendor        varchar(255),
    grade         varchar(20),
    unit          varchar(20),
    best_price    double precision,
    status        varchar(50),
    installation  varchar(50)
);

create table if not exists stock_type_maker (
    id            bigint generated by default as identity primary key,
    stock_type_id bigint references stock_type (id),
    stock_type_no varchar(50),
    maker         varchar(50),
    makers_ref    varchar(100),
    price         double precision,
    status        varchar(50)
);

create table if not exists stock_type_vendor (
    id            bigint generated by default as identity primary key,
    stock_type_id bigint references stock_type (id),
    stock_type_no varchar(50),
    vendor        varchar(255),
    price         double precision,
    lead_time     integer,
    status        varchar(50)
);

create table if not exists stock_grade (
    id            bigint generated by default as identity primary key,
    stock_type_id bigint references stock_type (id),
    stock_type_no varchar(50),
    grade         varchar(20),
    price_factor  double precision,
    description   varchar(255)
);

-- ===== 种子：makerRegistry（来自 mock/index.js lookups.makerRegistry） =====
insert into maker_register (code, name) values
('WART', 'Wärtsilä'),
('SHELL', 'Shell'),
('ABBM', 'ABB Marine'),
('ALFA', 'Alfa Laval'),
('AALB', 'Aalborg'),
('GRUN', 'Grundfos'),
('TYCO', 'Tyco International'),
('RRM', 'Rolls-Royce Marine'),
('SWEP', 'SWEP International'),
('MANE', 'MAN Energy Solutions'),
('CUMM', 'Cummins Inc.'),
('MACG', 'MacGregor / Cargotec'),
('USHA', 'Usha Martin'),
('CARR', 'Carrier Corporation'),
('SCHAT', 'Schat-Harding'),
('KIDDE', 'Kidde (Carrier Fire Products)'),
('FURU', 'Furuno Electric'),
('TTS', 'TTS (MacGregor Group)'),
('MANB', 'MAN B&W DIESEL A/S');

-- ===== 种子：示例组件与备件主数据 =====
insert into component (number, type_number, name, status, maker, type, installation)
values ('C-10001', 'CT-1001', 'ME Cylinder #1', 'In Use', 'WART', 'Liner', 'Traveller');

insert into stock_type (stock_type_no, description, maker, vendor, grade, unit, best_price, status, installation)
values ('ST-101', 'Cylinder Liner Gasket', 'WART', 'Wärtsilä Marine', 'A', 'pcs', 320, 'Active', 'Traveller');

insert into stock_type_maker (stock_type_id, stock_type_no, maker, makers_ref, price, status)
values (1, 'ST-101', 'WART', '1698466', 310, 'Approved');
