-- ============================================================
-- AMOS V2：Component Type 父子层级（children）
-- ------------------------------------------------------------
-- 为 component_type 增加自引用父子关系，支持多级类型树。
-- 采用 H2(PostgreSQL 兼容模式) 与 PostgreSQL 双兼容写法：
--   主键用 BIGINT GENERATED BY DEFAULT AS IDENTITY，而非 PG 专有的 bigserial。
-- 业务表一律只通过 Flyway 维护，不手工建表。
-- ============================================================

-- 父类型外键（可为空表示根节点）
alter table component_type
    add column if not exists parent_id bigint;

alter table component_type
    drop constraint if exists fk_component_type_parent;

alter table component_type
    add constraint fk_component_type_parent
        foreign key (parent_id) references component_type (id);

-- 父子层级表：一个父类型下可挂多个子类型（含跨类型引用）
create table if not exists component_type_children (
    id               bigint generated by default as identity primary key,
    parent_type_id   bigint not null,
    child_type_id    bigint not null,
    relation         varchar(50),
    constraint fk_ctc_parent foreign key (parent_type_id) references component_type (id),
    constraint fk_ctc_child  foreign key (child_type_id)  references component_type (id),
    constraint uq_ctc_pair   unique (parent_type_id, child_type_id)
);

-- 便于按父类型查子类型的索引
create index if not exists idx_ctc_parent on component_type_children (parent_type_id);
create index if not exists idx_ctc_child  on component_type_children (child_type_id);
