-- ============================================================
-- AMOS V3：Component Type 聚合子结构（定义 + 关联）
-- ------------------------------------------------------------
-- 补齐 component-types-slice.md 第 3 节规划的 V2 剩余内容：
--   comp_type_model 列 + 4 张子表（计数器定义 / 测点定义 /
--   关联类型 / 关联备件类型）。
-- 采用 H2(PostgreSQL 兼容模式) 与 PostgreSQL 双兼容写法：
--   主键用 BIGINT GENERATED BY DEFAULT AS IDENTITY，不写 bigserial。
-- 业务表一律只通过 Flyway 维护，不手工建表。
-- 注意：V2 文件名已被 component_type_children 占用，本脚本顺延为 V3，
--       不修改历史 migration（遵循 database-rewrite-guide.md 第 2.2/3.1 节）。
-- ============================================================

-- 3.1 component_type 补 comp_type_model（型号/机型描述截图字段）
alter table component_type
    add column if not exists comp_type_model varchar(100);

-- 3.2 类型级计数器定义（component_type_counter_def）
create table if not exists component_type_counter_def (
    id               bigint generated by default as identity primary key,
    component_type_id bigint not null,
    code             varchar(50) not null,
    description      varchar(255),
    unit             varchar(20),
    sort_order       integer default 0,
    constraint fk_ctcd_type  foreign key (component_type_id) references component_type (id),
    constraint uq_ctcd_pair  unique (component_type_id, code)
);

-- 3.3 类型级测点定义（component_type_measure_point_def）
create table if not exists component_type_measure_point_def (
    id               bigint generated by default as identity primary key,
    component_type_id bigint not null,
    code             varchar(50) not null,
    description      varchar(255),
    trend            varchar(20),
    unit             varchar(20),
    sort_order       integer default 0,
    constraint fk_ctmpd_type foreign key (component_type_id) references component_type (id),
    constraint uq_ctmpd_pair unique (component_type_id, code)
);

-- 3.4 关联类型（component_type_related_type）
create table if not exists component_type_related_type (
    id                        bigint generated by default as identity primary key,
    component_type_id         bigint not null,
    related_component_type_id bigint not null,
    constraint fk_ctrt_type    foreign key (component_type_id) references component_type (id),
    constraint fk_ctrt_related foreign key (related_component_type_id) references component_type (id),
    constraint uq_ctrt_pair    unique (component_type_id, related_component_type_id)
);

-- 3.5 关联备件类型（component_type_stock_type，Parts / Stock Types）
create table if not exists component_type_stock_type (
    id               bigint generated by default as identity primary key,
    component_type_id bigint not null,
    stock_type_id    bigint not null,
    makers_ref       varchar(100),
    quantity         double precision default 1,
    remarks          varchar(500),
    constraint fk_ctst_type  foreign key (component_type_id) references component_type (id),
    constraint fk_ctst_stock foreign key (stock_type_id) references stock_type (id),
    constraint uq_ctst_pair  unique (component_type_id, stock_type_id)
);

-- 便于按 component_type 反查子表的索引
create index if not exists idx_ctcd_type  on component_type_counter_def (component_type_id);
create index if not exists idx_ctmpd_type on component_type_measure_point_def (component_type_id);
create index if not exists idx_ctrt_type  on component_type_related_type (component_type_id);
create index if not exists idx_ctst_type  on component_type_stock_type (component_type_id);
