-- V4 System Foundation: installation / department / amos_user / role / user_role / user_department_access / user_option
-- H2 / PostgreSQL 双兼容（identity 主键 + varchar/text）。
-- 说明：带密码的用户（admin）由应用启动时的 SystemSeedRunner 注入（BCrypt 哈希需代码生成）；
--       此处仅建表并写入 installation/department/role 参考种子（幂等）。

create table if not exists installation (
    id    bigint generated by default as identity primary key,
    code  varchar(50)  not null,
    name  varchar(255),
    status varchar(50) not null default 'Active',
    constraint uk_installation_code unique (code)
);

create table if not exists department (
    id              bigint generated by default as identity primary key,
    installation_id bigint not null,
    code            varchar(50) not null,
    name            varchar(255),
    status          varchar(50) not null default 'Active',
    constraint fk_department_installation foreign key (installation_id) references installation (id),
    constraint uk_department_inst_code unique (installation_id, code)
);

create table if not exists amos_user (
    id            bigint generated by default as identity primary key,
    username      varchar(50) not null,
    display_name  varchar(255),
    password_hash varchar(255) not null,
    status        varchar(50) not null default 'Active',
    constraint uk_amos_user_username unique (username)
);

create table if not exists role (
    id   bigint generated by default as identity primary key,
    code varchar(50) not null,
    name varchar(255),
    constraint uk_role_code unique (code)
);

create table if not exists user_role (
    user_id bigint not null,
    role_id bigint not null,
    constraint fk_user_role_user foreign key (user_id) references amos_user (id),
    constraint fk_user_role_role foreign key (role_id) references role (id),
    primary key (user_id, role_id)
);

create table if not exists user_department_access (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null,
    installation_id bigint not null,
    department_id   bigint not null,
    constraint fk_uda_user foreign key (user_id) references amos_user (id),
    constraint fk_uda_installation foreign key (installation_id) references installation (id),
    constraint fk_uda_department foreign key (department_id) references department (id),
    constraint uk_uda unique (user_id, installation_id, department_id)
);

create table if not exists user_option (
    id       bigint generated by default as identity primary key,
    user_id  bigint not null,
    opt_key  varchar(100) not null,
    opt_value text,
    constraint fk_user_option_user foreign key (user_id) references amos_user (id),
    constraint uk_user_option unique (user_id, opt_key)
);

-- 基础参考种子（幂等）
insert into installation (code, name, status)
select 'Traveller', 'MV Traveller', 'Active'
where not exists (select 1 from installation where code = 'Traveller');

insert into department (installation_id, code, name, status)
select (select id from installation where code = 'Traveller'), 'ER', 'Engine Room', 'Active'
where not exists (
    select 1 from department
    where code = 'ER'
      and installation_id = (select id from installation where code = 'Traveller')
);

insert into role (code, name)
select 'ADMIN', 'Administrator'
where not exists (select 1 from role where code = 'ADMIN');
