-- ============================================================
-- AMOS V5：Registers（基础注册表）
-- 10 个 register：makers(扩列) / vendors / locations / units /
-- currencies / function_criticality / job_class / trade /
-- discipline / budget_code
-- 采用 H2(PostgreSQL 兼容模式) 与 PostgreSQL 双兼容写法：
--   主键用 BIGINT GENERATED BY DEFAULT AS IDENTITY，不写 bigserial。
--   幂等种子使用 insert ... select ... where not exists（H2/PG 均支持）。
-- 注意：V1-V4 已被占用，本脚本顺延为 V5（不改历史 migration）。
-- ============================================================

-- 0. maker_register 扩列（status / remarks）
-- 注意：H2 不支持在单条 ALTER TABLE 中逗号分隔多个 ADD COLUMN，
--      故每个字段单独一条语句（PostgreSQL 同样兼容）。
alter table maker_register add column if not exists status  varchar(50) not null default 'ACTIVE';
alter table maker_register add column if not exists remarks varchar(1000);

-- 1. vendor_register
create table if not exists vendor_register (
    id            bigint generated by default as identity primary key,
    vendor_no     varchar(50)  not null unique,
    name          varchar(255),
    country       varchar(100),
    currency      varchar(10),
    payment_terms varchar(100),
    status        varchar(50)  not null default 'ACTIVE',
    remarks       varchar(1000)
);

-- 2. location_register（安装地点作用域 + 自引用父级）
create table if not exists location_register (
    id                bigint generated by default as identity primary key,
    installation_id   bigint,
    code              varchar(50)  not null,
    name              varchar(255),
    parent_location_id bigint,
    location_type     varchar(50),
    status            varchar(50)  not null default 'ACTIVE',
    remarks           varchar(1000),
    constraint uq_location_install_code unique (installation_id, code),
    constraint fk_location_parent foreign key (parent_location_id) references location_register (id)
);

-- 3. unit_register
create table if not exists unit_register (
    id          bigint generated by default as identity primary key,
    code        varchar(50) not null unique,
    name        varchar(255),
    description varchar(1000),
    status      varchar(50) not null default 'ACTIVE'
);

-- 4. currency_register
create table if not exists currency_register (
    id     bigint generated by default as identity primary key,
    code   varchar(10) not null unique,
    name   varchar(255),
    symbol varchar(10),
    status varchar(50) not null default 'ACTIVE'
);

-- 5. function_criticality（active 布尔）
create table if not exists function_criticality (
    id         bigint generated by default as identity primary key,
    degree     varchar(50) not null unique,
    description varchar(255),
    color      varchar(20),
    sort_order integer     not null default 0,
    active     boolean     not null default true
);

-- 6. job_class
create table if not exists job_class (
    id          bigint generated by default as identity primary key,
    code        varchar(50) not null unique,
    name        varchar(255),
    description varchar(1000),
    status      varchar(50) not null default 'ACTIVE'
);

-- 7. trade
create table if not exists trade (
    id          bigint generated by default as identity primary key,
    code        varchar(50) not null unique,
    name        varchar(255),
    description varchar(1000),
    status      varchar(50) not null default 'ACTIVE'
);

-- 8. discipline
create table if not exists discipline (
    id          bigint generated by default as identity primary key,
    code        varchar(50) not null unique,
    name        varchar(255),
    description varchar(1000),
    status      varchar(50) not null default 'ACTIVE'
);

-- 9. budget_code
create table if not exists budget_code (
    id                bigint generated by default as identity primary key,
    code              varchar(50) not null unique,
    name              varchar(255),
    parent_budget_code varchar(50),
    description       varchar(1000),
    status            varchar(50) not null default 'ACTIVE'
);

-- ===== 幂等参考种子（仅插入一次） =====
insert into vendor_register (vendor_no, name, country, currency, payment_terms, status)
select 'V-WART', 'Wärtsilä Marine', 'Finland', 'EUR', 'Net 30', 'ACTIVE'
where not exists (select 1 from vendor_register where vendor_no = 'V-WART');

insert into location_register (installation_id, code, name, location_type, status)
select (select id from installation where code = 'Traveller'), 'ER', 'Engine Room', 'Space', 'ACTIVE'
where not exists (select 1 from location_register where code = 'ER' and installation_id = (select id from installation where code = 'Traveller'));

insert into unit_register (code, name, description, status)
select 'PCS', 'Pieces', 'Individual count', 'ACTIVE'
where not exists (select 1 from unit_register where code = 'PCS');

insert into currency_register (code, name, symbol, status)
select 'EUR', 'Euro', '€', 'ACTIVE'
where not exists (select 1 from currency_register where code = 'EUR');

insert into function_criticality (degree, description, color, sort_order, active)
select 'CRIT', 'Critical', '#d32f2f', 1, true
where not exists (select 1 from function_criticality where degree = 'CRIT');

insert into job_class (code, name, description, status)
select 'CLASS-A', 'Class A Overhaul', 'Major planned overhaul', 'ACTIVE'
where not exists (select 1 from job_class where code = 'CLASS-A');

insert into trade (code, name, description, status)
select 'MECH', 'Mechanical', 'Mechanical trade', 'ACTIVE'
where not exists (select 1 from trade where code = 'MECH');

insert into discipline (code, name, description, status)
select 'WELD', 'Welding', 'Welding discipline', 'ACTIVE'
where not exists (select 1 from discipline where code = 'WELD');

insert into budget_code (code, name, description, status)
select 'BG-OPS', 'Operations', 'Operating budget', 'ACTIVE'
where not exists (select 1 from budget_code where code = 'BG-OPS');
