-- ============================================================
-- AMOS V8：Components 模块完善
-- ------------------------------------------------------------
-- 1) component 增加层级/类型模型/时间戳字段
-- 2) component_counter 补充计数器管理字段
-- 3) 新建 component_measure_point / component_status_log /
--    component_function_history / component_archive
-- H2(PostgreSQL 兼容模式) 与 PostgreSQL 双兼容，全部 IF NOT EXISTS
-- 幂等，遵循「不改动历史 migration」。
-- ============================================================

-- 1) component 表补列
alter table component
    add column if not exists parent_component      varchar(50);
alter table component
    add column if not exists component_type_model  varchar(100);
alter table component
    add column if not exists date_created          varchar(20);
alter table component
    add column if not exists date_modified         varchar(20);

create index if not exists idx_component_installation on component (installation);
create index if not exists idx_component_department  on component (department);
create index if not exists idx_component_status       on component (status);
create index if not exists idx_component_parent       on component (parent_component);

-- 2) component_counter 表补列
alter table component_counter
    add column if not exists latest_zeroed_date  varchar(20);
alter table component_counter
    add column if not exists start_value         numeric(18, 4);
alter table component_counter
    add column if not exists average             numeric(18, 4);
alter table component_counter
    add column if not exists calculate           varchar(10);

-- 3) 组件测点（对应前端 Measure Points 子表）
create table if not exists component_measure_point (
    id             bigint generated by default as identity primary key,
    component_id   bigint references component (id),
    code           varchar(50),
    description    varchar(200),
    unit           varchar(20),
    trend          varchar(20),
    reading        varchar(50),
    last_read_date varchar(20)
);
create index if not exists idx_cmp_component on component_measure_point (component_id);

-- 4) 组件状态变更日志（不可变）
create table if not exists component_status_log (
    id            bigint generated by default as identity primary key,
    component_id  bigint,
    component_no  varchar(50),
    old_status    varchar(50),
    new_status    varchar(50),
    reason        varchar(200),
    changed_by    varchar(50),
    changed_at    varchar(20)
);
create index if not exists idx_csl_component on component_status_log (component_id);
create index if not exists idx_csl_component_no on component_status_log (component_no);

-- 5) 组件安装/拆卸历史（Functions Performed）
create table if not exists component_function_history (
    id                bigint generated by default as identity primary key,
    component_id      bigint,
    component_no      varchar(50),
    function_no       varchar(50),
    function_description varchar(200),
    location          varchar(100),
    action            varchar(20),
    performed_by      varchar(50),
    performed_at      varchar(20)
);
create index if not exists idx_cfh_component on component_function_history (component_id);
create index if not exists idx_cfh_component_no on component_function_history (component_no);

-- 6) 组件档案（三种：component / transfer / status）
create table if not exists component_archive (
    id             bigint generated by default as identity primary key,
    component_no   varchar(50),
    kind           varchar(20),
    from_department varchar(100),
    to_department  varchar(100),
    archive_date   varchar(20),
    data           varchar(2000)
);
create index if not exists idx_ca_component_no on component_archive (component_no);
