-- ============================================================
-- AMOS V9：Functions（功能位置 / SFI）模块
-- ------------------------------------------------------------
-- 1) maintenance_function      功能位置主表（父子用 parent_function_no 字符串表达）
-- 2) function_counter          功能位置计数器子表
-- 3) component_function_rotation 组件安装/拆卸轮次日志（不可变）
-- H2(PostgreSQL 兼容模式) 与 PostgreSQL 双兼容，全部 IF NOT EXISTS，幂等。
-- 不改动历史 migration。
-- ============================================================

-- 1) 功能位置主表
create table if not exists maintenance_function (
    id                    bigint generated by default as identity primary key,
    function_no           varchar(50)  not null,
    installation          varchar(50),
    department            varchar(100),
    description           varchar(255),
    reference             varchar(100),
    parent_function_no    varchar(50),
    status                varchar(50),
    location              varchar(100),
    criticality           varchar(50),
    installed_component_no varchar(50),
    sfi_code              varchar(50),
    system                varchar(100),
    sub_system            varchar(100),
    remarks               varchar(1000),
    serial_no             varchar(100),
    maker                 varchar(100),
    model                 varchar(100),
    tag_no                varchar(100),
    asset_value           numeric(18, 2),
    acquisition_date      varchar(20),
    currency              varchar(10),
    depreciation          numeric(18, 2),
    constraint uq_function_install_no unique (installation, function_no)
);
create index if not exists idx_mf_installation on maintenance_function (installation);
create index if not exists idx_mf_department  on maintenance_function (department);
create index if not exists idx_mf_status       on maintenance_function (status);
create index if not exists idx_mf_parent       on maintenance_function (parent_function_no);
create index if not exists idx_mf_criticality  on maintenance_function (criticality);
create index if not exists idx_mf_comp         on maintenance_function (installed_component_no);

-- 2) 功能位置计数器子表
create table if not exists function_counter (
    id            bigint generated by default as identity primary key,
    function_id   bigint references maintenance_function (id) on delete cascade,
    code          varchar(50),
    description   varchar(200),
    unit          varchar(20),
    last_value    numeric(18, 4)
);
create index if not exists idx_fc_function on function_counter (function_id);

-- 3) 组件安装/拆卸轮次日志（不可变，支撑 Rotation Log）
create table if not exists component_function_rotation (
    id               bigint generated by default as identity primary key,
    function_id      bigint references maintenance_function (id) on delete cascade,
    component_id     bigint,
    component_no     varchar(50),
    component_name   varchar(200),
    action           varchar(20),
    performed_by     varchar(50),
    performed_at     varchar(20),
    details          varchar(1000),
    new_location     varchar(100),
    new_status       varchar(50),
    installed_at     varchar(20),
    removed_at       varchar(20)
);
create index if not exists idx_cfr_function on component_function_rotation (function_id);
create index if not exists idx_cfr_component on component_function_rotation (component_id);
create index if not exists idx_cfr_compno   on component_function_rotation (component_no);

-- 4) 种子：Traveller 少量功能位置（父子层级，无安装组件），支撑后端化窗口演示
insert into maintenance_function (function_no, installation, department, description, reference, parent_function_no, status, location, criticality, sfi_code, system, sub_system)
select 'FN-ENG-01', 'Traveller', 'Engine Room', 'Main Engine', 'ME', null, 'In Use', 'Engine Room', 'High', '21000000', 'Machinery', 'Propulsion'
where not exists (select 1 from maintenance_function where function_no = 'FN-ENG-01' and installation = 'Traveller');

insert into maintenance_function (function_no, installation, department, description, reference, parent_function_no, status, location, criticality, sfi_code, system, sub_system)
select 'FN-ENG-02', 'Traveller', 'Engine Room', 'Auxiliary Boiler A', 'AUX BOILER A', 'FN-ENG-01', 'In Use', 'Engine Room', 'High', '23000000', 'Machinery', 'Boiler'
where not exists (select 1 from maintenance_function where function_no = 'FN-ENG-02' and installation = 'Traveller');

insert into maintenance_function (function_no, installation, department, description, reference, parent_function_no, status, location, criticality, sfi_code, system, sub_system)
select 'FN-ENG-03', 'Traveller', 'Engine Room', 'Auxiliary Boiler B', 'AUX BOILER B', 'FN-ENG-01', 'In Use', 'Engine Room', 'High', '23000000', 'Machinery', 'Boiler'
where not exists (select 1 from maintenance_function where function_no = 'FN-ENG-03' and installation = 'Traveller');

insert into maintenance_function (function_no, installation, department, description, reference, parent_function_no, status, location, criticality, sfi_code, system, sub_system)
select 'FN-DECK-01', 'Traveller', 'Deck', 'Deck Crane', 'DCRANE', null, 'In Use', 'Deck', 'Medium', '12000000', 'Hull', 'Deck Crane'
where not exists (select 1 from maintenance_function where function_no = 'FN-DECK-01' and installation = 'Traveller');
